import Link from "next/link";
import { AdminShell } from "@/components/admin/admin-shell";
import { getAdminInventoryCounts } from "@/server/admin/inventory";
import { prisma } from "@/server/db/prisma";
import { requireAdminPage } from "@/server/security/admin-auth";
const PAGE_SIZE = 20;
function valueOf(value: string | string[] | undefined): string { return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }
export default async function SellerReviewsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const admin = await requireAdminPage(); const query = await searchParams; const search = valueOf(query.q).trim().slice(0, 100); const requestedPage = Number.parseInt(valueOf(query.page) || "1", 10); const page = Number.isSafeInteger(requestedPage) && requestedPage > 0 ? requestedPage : 1;
  const where = { status: "SUBMITTED" as const, ...(search ? { OR: [{ name: { contains: search, mode: "insensitive" as const } }, { seller: { displayName: { contains: search, mode: "insensitive" as const } } }] } : {}) };
  const [counts, total] = await Promise.all([getAdminInventoryCounts(), prisma.sellerProductDraft.count({ where })]);
  const pageCount = Math.max(1, Math.ceil(total / PAGE_SIZE)); const currentPage = Math.min(page, pageCount);
  const drafts = await prisma.sellerProductDraft.findMany({ where, include: { seller: { select: { displayName: true } } }, orderBy: [{ createdAt: "asc" }, { id: "asc" }], skip: (currentPage - 1) * PAGE_SIZE, take: PAGE_SIZE });
  const pageUrl = (nextPage: number) => { const params = new URLSearchParams(); if (search) params.set("q", search); params.set("page", String(nextPage)); return `/admin/seller-products/reviews?${params.toString()}`; };
  return <AdminShell active="sellers" counts={counts} email={admin.email} eyebrow="Seller products" title="Antrean review produk" description="Daftar ini hanya untuk pencarian, ringkasan, dan navigasi. Buka satu draft untuk mengambil keputusan review."><div className="seller-admin-actions"><Link className="button button-quiet" href="/admin/sellers">← Semua seller</Link></div><section className="panel"><form className="admin-filter-bar" method="get"><label htmlFor="seller-review-search">Cari produk atau seller</label><div className="admin-filter-controls"><input id="seller-review-search" name="q" defaultValue={search} placeholder="Nama produk / seller" /><button className="button button-primary" type="submit">Cari</button></div></form><div className="seller-review-summary"><strong>{total} draft menunggu review</strong><span>Halaman {currentPage} dari {pageCount}</span></div>{drafts.length ? <div className="seller-table-wrap"><table className="seller-table"><thead><tr><th>Produk</th><th>Seller</th><th>Harga</th><th>Diajukan</th><th>Aksi</th></tr></thead><tbody>{drafts.map((draft) => <tr key={draft.id}><td><strong>{draft.name}</strong><small>Versi {draft.revision}</small></td><td>{draft.seller.displayName}</td><td>Rp {draft.price.toLocaleString("id-ID")}</td><td>{draft.createdAt.toLocaleDateString("id-ID")}</td><td><Link className="button button-small" href={`/admin/seller-products/reviews/${draft.id}`}>Buka review</Link></td></tr>)}</tbody></table></div> : <div className="seller-empty"><strong>{search ? "Tidak ada draft yang cocok" : "Belum ada draft menunggu review"}</strong><p>{search ? "Ubah kata kunci pencarian." : "Draft seller yang sudah diajukan akan muncul di sini."}</p></div>}{pageCount > 1 ? <nav className="seller-admin-actions" aria-label="Paginasi review">{currentPage > 1 ? <Link className="button button-quiet" href={pageUrl(currentPage - 1)}>← Sebelumnya</Link> : null}{currentPage < pageCount ? <Link className="button button-quiet" href={pageUrl(currentPage + 1)}>Berikutnya →</Link> : null}</nav> : null}</section></AdminShell>;
}
