import type { TelegramLocale } from "@/server/telegram/i18n";

const CATALOG_COPY = {
  id: {
    productDetailTitle: "DETAIL PRODUK",
    chooseVariantTitle: "PILIH VARIAN",
    priceLabel: "Harga",
    stockReady: (count: number) => `Stok siap: ${count}`,
    automaticDelivery: "Pengiriman otomatis setelah lunas",
    checkoutLocked: (count: number) => `${count} stok sedang dikunci checkout aktif.`,
    retryAfterInvoice: "Coba lagi setelah pembayaran selesai atau invoice kedaluwarsa.",
    preorderWaitsForReservation: "Preorder belum dibuka selama stok masih dalam masa reservasi.",
    preorderStatus: "Status: PREORDER",
    estimate: (value: string) => `Estimasi: ${value}`,
    estimateFallback: "akan diinformasikan admin",
    remainingSlots: (value: number | string) => `Slot tersisa: ${value}`,
    unlimited: "tanpa batas",
    preorderFifo: "Order lunas diproses FIFO saat stok sehat masuk.",
    preorderFull: "Status: PREORDER PENUH",
    outOfStock: "Status: stok habis",
    choosePreorderQuantity: "Pilih jumlah preorder",
    chooseQuantity: "Pilih jumlah",
    checkStockAgain: "Cek stok lagi",
    enableRestockNotification: "Aktifkan notif restock",
    backToVariants: (name: string) => `Varian ${name}`,
    catalog: "Katalog",
    search: "Cari",
    variantPage: (count: number, page: string) => `${count} varian - Halaman ${page}`,
    availabilityLegend: "tersedia  📥 preorder  ⏳ dikunci  ❌ habis",
    variantHint: "Tekan varian untuk melihat detail. Nomor varian juga bisa diketik.",
    noMatchingVariant: (name: string, search: string) => `Tidak ada varian ${name} yang cocok dengan \"${search}\".`,
    noActiveVariant: (name: string) => `${name} belum memiliki varian aktif.`,
    backToCatalog: "Kembali ke katalog",
    maintenanceCatalog: "Katalog tetap dapat dilihat, tetapi checkout baru ditutup.",
    maintenanceVariants: "Varian tetap dapat dilihat, tetapi checkout baru ditutup.",
    productNotFound: (search: string) => `Produk \"${search}\" tidak ditemukan.`,
    noActiveProduct: "Belum ada produk aktif saat ini.",
    searchAgain: "Cari lagi",
    back: "Kembali",
    categoryOffer: (count: number, price: string) => `${count} pilihan - mulai ${price}`,
    catalogResultsTitle: (search: string) => `HASIL: \"${search}\"`,
    catalogTitle: "KATALOG PRODUK",
    catalogCount: (count: number, page: string) => `${count} kategori/produk - Halaman ${page}`,
    catalogHint: "Pilih produk atau kategori. Tekan tombolnya untuk melihat detail.",
    searchProduct: "Cari produk",
    menu: "Menu",
    searchPrompt: "Cari produk\n\nKirim nama kategori atau varian.\nContoh: ChatGPT, Codex, K12.",
    invalidSearch: "Kata pencarian produk harus 2-50 karakter.",
    newProductTitle: "PRODUK BARU",
    readyFiles: (count: number) => `Stok siap: ${count} stok`,
    preorderLabel: (value: string) => `Preorder: ${value}`,
    buyInstruction: "Gunakan tombol di bawah untuk membeli.",
    buyNow: "Beli sekarang",
    viewAllProducts: "Lihat semua produk",
    restockTitle: "STOK BARU MASUK",
    newlyAdded: (count: number) => `Baru ditambahkan: ${count} stok`,
    availableNow: (count: number) => `Tersedia sekarang: ${count} stok`,
    buyNowInstruction: "Gunakan tombol di bawah untuk membeli sekarang.",
    soldOutTitle: "STOK SIAP HABIS",
    readyNowEmpty: "Stok siap sekarang: 0 stok",
    reservedFiles: (count: number) => `${count} stok sedang dikunci checkout aktif`,
    waitForRestock: "Tunggu notifikasi restock berikutnya.",
    openLatestStatus: "Buka detail produk untuk melihat status terbaru.",
    viewProduct: "Lihat produk",
    viewCatalog: "Lihat katalog",
    noQuantityCapacity: "Stok siap dan slot preorder sedang tidak tersedia.",
    readyAccounts: (count: number) => `Stok siap: ${count} akun.`,
    maxOrderNow: (count: number) => `Maksimal pesanan saat ini: ${count} akun.`,
    maxIncludingPreorder: (count: number) => `Maksimal termasuk preorder: ${count} akun.`,
    accountUnits: (count: number) => `${count} akun`,
    quantityTooLarge: "Jumlah terlalu besar. Masukkan angka bulat yang lebih kecil.",
    numbersOnly: "Masukkan angka saja, contoh: 7.",
    minimumQuantity: "Jumlah minimal 1 akun.",
    aboveGlobalLimit: (quantity: number, maximum: number) => `Jumlah ${quantity} melebihi batas sekali transaksi. Maksimal ${maximum} akun.`,
    noOrderCapacity: "Stok siap atau slot preorder sedang tidak tersedia. Silakan cek lagi nanti.",
    readyQuantityLimit: (ready: number, maximum: number) => `Stok siap saat ini ${ready} akun. Pilih maksimal ${maximum} akun.`,
    productQuantityLimit: (quantity: number, maximum: number) => `Jumlah ${quantity} melebihi kapasitas produk saat ini. Maksimal ${maximum} akun termasuk preorder.`,
    unitPrice: "Harga per akun",
    chooseOrTypeQuantity: (range: string) => `Tekan jumlah di bawah atau langsung ketik angka ${range}.`,
    uniqueStockPerUnit: "Setiap unit menerima file stok yang berbeda.",
    productCannotBeOrdered: "Produk belum bisa dipesan saat ini. Silakan cek lagi nanti.",
    typeCustomQuantity: "Jumlah custom",
    sendQuantity: (range: string) => `Kirim angka jumlah akun yang ingin dibeli (${range}).`,
    example: "Contoh",
    mainMenu: "Menu utama",
    unavailableProduct: "Produk sudah tidak tersedia. Silakan buka katalog lagi.",
    integerQuantity: "Jumlah harus berupa angka bulat.",
    availableRange: (range: string) => `Rentang tersedia sekarang: ${range}.`,
    invalidSelection: "Nomor pilihan tidak ada di halaman ini.",
    chooseNumbers: (numbers: string) => `Pilih nomor: ${numbers}.`,
    backToVariantList: "Kembali ke varian",
  },
  en: {
    productDetailTitle: "PRODUCT DETAILS",
    chooseVariantTitle: "CHOOSE A VARIANT",
    priceLabel: "Price",
    stockReady: (count: number) => `Ready stock: ${count}`,
    automaticDelivery: "Automatic delivery after payment",
    checkoutLocked: (count: number) => `${count} item(s) are reserved by active checkouts.`,
    retryAfterInvoice: "Try again after payment is completed or the invoice expires.",
    preorderWaitsForReservation: "Preorder stays closed while ready stock is still reserved.",
    preorderStatus: "Status: PREORDER",
    estimate: (value: string) => `Estimate: ${value}`,
    estimateFallback: "will be provided by admin",
    remainingSlots: (value: number | string) => `Remaining slots: ${value}`,
    unlimited: "unlimited",
    preorderFifo: "Paid orders are fulfilled FIFO when healthy stock arrives.",
    preorderFull: "Status: PREORDER FULL",
    outOfStock: "Status: out of stock",
    choosePreorderQuantity: "Choose preorder quantity",
    chooseQuantity: "Choose quantity",
    checkStockAgain: "Check stock again",
    enableRestockNotification: "Enable restock alerts",
    backToVariants: (name: string) => `${name} variants`,
    catalog: "Catalog",
    search: "Search",
    variantPage: (count: number, page: string) => `${count} variants - Page ${page}`,
    availabilityLegend: "available  📥 preorder  ⏳ reserved  ❌ sold out",
    variantHint: "Press a variant to view details. You can also type its number.",
    noMatchingVariant: (name: string, search: string) => `No ${name} variant matches \"${search}\".`,
    noActiveVariant: (name: string) => `${name} does not have an active variant yet.`,
    backToCatalog: "Back to catalog",
    maintenanceCatalog: "You can still browse the catalog, but new checkouts are closed.",
    maintenanceVariants: "You can still browse variants, but new checkouts are closed.",
    productNotFound: (search: string) => `Product \"${search}\" was not found.`,
    noActiveProduct: "There are no active products right now.",
    searchAgain: "Search again",
    back: "Back",
    categoryOffer: (count: number, price: string) => `${count} options - from ${price}`,
    catalogResultsTitle: (search: string) => `RESULTS: \"${search}\"`,
    catalogTitle: "PRODUCT CATALOG",
    catalogCount: (count: number, page: string) => `${count} categories/products - Page ${page}`,
    catalogHint: "Choose a product or category. Press a button to view details.",
    searchProduct: "Search products",
    menu: "Menu",
    searchPrompt: "Search products\n\nSend a category or variant name.\nExample: ChatGPT, Codex, K12.",
    invalidSearch: "The product search must contain 2-50 characters.",
    newProductTitle: "NEW PRODUCT",
    readyFiles: (count: number) => `Ready stock: ${count} units`,
    preorderLabel: (value: string) => `Preorder: ${value}`,
    buyInstruction: "Use the button below to purchase.",
    buyNow: "Buy now",
    viewAllProducts: "View all products",
    restockTitle: "NEW STOCK AVAILABLE",
    newlyAdded: (count: number) => `Newly added: ${count} stock units`,
    availableNow: (count: number) => `Available now: ${count} stock units`,
    buyNowInstruction: "Use the button below to purchase now.",
    soldOutTitle: "READY STOCK SOLD OUT",
    readyNowEmpty: "Ready stock now: 0 units",
    reservedFiles: (count: number) => `${count} stock units are reserved by active checkouts`,
    waitForRestock: "Wait for the next restock notification.",
    openLatestStatus: "Open the product details to see the latest status.",
    viewProduct: "View product",
    viewCatalog: "View catalog",
    noQuantityCapacity: "Ready stock and preorder slots are currently unavailable.",
    readyAccounts: (count: number) => `Ready stock: ${count} accounts.`,
    maxOrderNow: (count: number) => `Current maximum order: ${count} accounts.`,
    maxIncludingPreorder: (count: number) => `Maximum including preorder: ${count} accounts.`,
    accountUnits: (count: number) => `${count} accounts`,
    quantityTooLarge: "The quantity is too large. Enter a smaller whole number.",
    numbersOnly: "Enter numbers only, for example: 7.",
    minimumQuantity: "The minimum quantity is 1 account.",
    aboveGlobalLimit: (quantity: number, maximum: number) => `Quantity ${quantity} exceeds the per-order limit. Maximum: ${maximum} accounts.`,
    noOrderCapacity: "Ready stock and preorder slots are unavailable. Please check again later.",
    readyQuantityLimit: (ready: number, maximum: number) => `Ready stock is ${ready} accounts. Choose at most ${maximum} accounts.`,
    productQuantityLimit: (quantity: number, maximum: number) => `Quantity ${quantity} exceeds current product capacity. Maximum: ${maximum} accounts including preorder.`,
    unitPrice: "Price per account",
    chooseOrTypeQuantity: (range: string) => `Press a quantity below or type a number from ${range}.`,
    uniqueStockPerUnit: "Each unit receives a different stock file.",
    productCannotBeOrdered: "This product cannot be ordered right now. Please check again later.",
    typeCustomQuantity: "Custom quantity",
    sendQuantity: (range: string) => `Send the number of accounts you want to buy (${range}).`,
    example: "Example",
    mainMenu: "Main menu",
    unavailableProduct: "This product is no longer available. Please open the catalog again.",
    integerQuantity: "Quantity must be a whole number.",
    availableRange: (range: string) => `Currently available range: ${range}.`,
    invalidSelection: "That option number is not on this page.",
    chooseNumbers: (numbers: string) => `Choose a number: ${numbers}.`,
    backToVariantList: "Back to variants",
  },
} as const;

export function catalogCopy(locale: TelegramLocale) {
  return CATALOG_COPY[locale];
}
