"""Build a small local icon set from a pinned Simple Icons archive + public catalog.

No npm dependency or downloaded code is executed. Run manually when refreshing
catalog branding; unmatched/new services retain the neutral UI fallback.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import tarfile
import unicodedata

ROOT = Path(__file__).resolve().parents[1]

def normalized(value):
    return re.sub(r"[^a-z0-9]", "", unicodedata.normalize("NFKD", value).lower())

parser = argparse.ArgumentParser()
parser.add_argument("--archive", required=True)
parser.add_argument("--catalog", default=str(ROOT / "design/sms/provider-services-20260921.json"))
args = parser.parse_args()
services = json.loads(Path(args.catalog).read_text(encoding="utf-8-sig"))
target = ROOT / "storefront/public/sms/brands"
target.mkdir(parents=True, exist_ok=True)
mapping, used = {}, {}
overrides = {
    "openaichatgpt": "openai", "openai": "openai", "chatgpt": "openai",
    "googlegmail": "google", "google": "google", "gmail": "google",
}
with tarfile.open(args.archive) as archive:
    icons = json.load(archive.extractfile("package/data/simple-icons.json"))
    lookup = {}
    for icon in icons:
        for name in [icon["title"], icon["slug"], *icon.get("aliases", {}).get("aka", [])]:
            lookup.setdefault(normalized(name), icon)
    for service in services:
        name = service["name"]
        key = normalized(name)
        requested = overrides.get(key, key)
        icon = lookup.get(requested)
        # Slash-separated provider labels sometimes group aliases of one brand.
        if not icon and requested != "openai":
            icon = lookup.get(normalized(name.split("/")[0]))
        if requested == "openai":
            slug = "openai"
            content = (ROOT / "design/sms/brand-sources/openai.svg").read_bytes()
            source = "https://cdn.jsdelivr.net/npm/simple-icons@13.21.0/icons/openai.svg"
            extension = "svg"
        elif icon:
            slug = icon["slug"]
            if not re.fullmatch(r"[a-z0-9]+", slug):
                continue
            google = ROOT / "design/sms/brand-sources/google.png"
            if slug == "google" and google.exists():
                content, extension = google.read_bytes(), "png"
                source = "https://www.gstatic.com/images/branding/product/2x/googleg_48dp.png"
            else:
                content = archive.extractfile(f"package/icons/{slug}.svg").read()
                if len(content) > 32768:
                    continue
                text = content.decode("utf-8")
                if re.search(r"<script|<!DOCTYPE|<!ENTITY|\son\w+=|(?:href|src)=", text, re.I):
                    raise ValueError(f"Unexpected SVG content for {slug}")
                text = text.replace("<svg ", f'<svg fill="#{icon["hex"]}" ', 1)
                content, extension, source = text.encode(), "svg", icon["source"]
        else:
            continue
        digest = hashlib.sha256(content).hexdigest()[:10]
        filename = f"{slug}.{digest}.{extension}"
        (target / filename).write_bytes(content)
        mapping[key] = "/sms/brands/" + filename
        used[filename] = {"brand": slug, "source": source, "bytes": len(content)}
    (target / "LICENSE-simple-icons.md").write_bytes(archive.extractfile("package/LICENSE.md").read())

module = "// Generated by scripts/sync_sms_brand_assets.py; public brand identifiers only.\n"
module += "export const smsBrandLogos: Record<string, string> = " + json.dumps(mapping, ensure_ascii=True, indent=2) + ";\n"
(ROOT / "storefront/src/lib/sms-brand-logos.ts").write_text(module, encoding="utf-8")
(ROOT / "design/sms/brand-assets.json").write_text(json.dumps({"simpleIconsVersion": "16.32.0", "totalServices": len(services), "mappedServices": len(mapping), "assets": used}, indent=2), encoding="utf-8")
print(json.dumps({"services": len(services), "mappedServices": len(mapping), "distinctIcons": len(used), "totalIconBytes": sum(x["bytes"] for x in used.values())}))
